#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AdditionalEntriesIndicator

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AdditionalEntriesIndicator.AdditionalEntriesIndicator_C
// 0x0008 (0x0240 - 0x0238)
class UAdditionalEntriesIndicator_C final : public UCommonUserWidget
{
public:
	class UImage*                                 Image_0;                                           // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AdditionalEntriesIndicator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AdditionalEntriesIndicator_C")
	}
	static class UAdditionalEntriesIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAdditionalEntriesIndicator_C>();
	}
};
DUMPER7_ASSERTS_UAdditionalEntriesIndicator_C;

}

