#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaCustomizationBannerButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaCustomizationBannerButton.AthenaCustomizationBannerButton_C
// 0x0018 (0x08B8 - 0x08A0)
class UAthenaCustomizationBannerButton_C final : public UCommonButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08A0(0x0008)(Transient, DuplicateTransient)
	class UNormalBangWrapper_C*                   NormalBangWrapper;                                 // 0x08A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPlayerBanner_C*                        PlayerBanner;                                      // 0x08B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_AthenaCustomizationBannerButton(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaCustomizationBannerButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaCustomizationBannerButton_C")
	}
	static class UAthenaCustomizationBannerButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaCustomizationBannerButton_C>();
	}
};
DUMPER7_ASSERTS_UAthenaCustomizationBannerButton_C;

}

