#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_AthenaAlwaysLoadedContentHack

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_AthenaAlwaysLoadedContentHack.B_AthenaAlwaysLoadedContentHack_C
// 0x0028 (0x03B0 - 0x0388)
class AB_AthenaAlwaysLoadedContentHack_C final : public AActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UObject*>                        HardObjectList;                                    // 0x0390(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TArray<class UClass*>                         HardClassList;                                     // 0x03A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_AthenaAlwaysLoadedContentHack_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_AthenaAlwaysLoadedContentHack_C")
	}
	static class AB_AthenaAlwaysLoadedContentHack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_AthenaAlwaysLoadedContentHack_C>();
	}
};
DUMPER7_ASSERTS_AB_AthenaAlwaysLoadedContentHack_C;

}

