#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Bullet_Sniper

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Prj_Bullet_Sniper.B_Prj_Bullet_Sniper_C
// 0x0020 (0x0830 - 0x0810)
class AB_Prj_Bullet_Sniper_C final : public AFortProjectileAthena
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0810(0x0008)(Transient, DuplicateTransient)
	class UParticleSystemComponent*               P_SR_Ribbon_SmokeTrail;                            // 0x0818(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBulletWhipTrackerComponent_C*          BulletWhipTrackerComponent;                        // 0x0820(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               P_Trail;                                           // 0x0828(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_Prj_Bullet_Sniper(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void OnTouched(class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FHitResult& HitResult, bool bIsOverlap);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_Prj_Bullet_Sniper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_Prj_Bullet_Sniper_C")
	}
	static class AB_Prj_Bullet_Sniper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Prj_Bullet_Sniper_C>();
	}
};
DUMPER7_ASSERTS_AB_Prj_Bullet_Sniper_C;

}

