#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Border_AngledTab_LBlue_Edge

#include "Basic.hpp"

#include "Border_TabM_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border_AngledTab_LBlue_Edge.Border_AngledTab_LBlue_Edge_C
// 0x0000 (0x00B8 - 0x00B8)
class UBorder_AngledTab_LBlue_Edge_C final : public UBorder_TabM_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Border_AngledTab_LBlue_Edge_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Border_AngledTab_LBlue_Edge_C")
	}
	static class UBorder_AngledTab_LBlue_Edge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_AngledTab_LBlue_Edge_C>();
	}
};
DUMPER7_ASSERTS_UBorder_AngledTab_LBlue_Edge_C;

}

