#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Border_Bottom_Box_Rounded

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-Bottom-Box-Rounded.Border-Bottom-Box-Rounded_C
// 0x0000 (0x00B8 - 0x00B8)
class UBorder_Bottom_Box_Rounded_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Border-Bottom-Box-Rounded_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Border-Bottom-Box-Rounded_C")
	}
	static class UBorder_Bottom_Box_Rounded_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_Bottom_Box_Rounded_C>();
	}
};
DUMPER7_ASSERTS_UBorder_Bottom_Box_Rounded_C;

}

