#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ZT_Survival

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ZT_Survival.BP_ZT_Survival_C
// 0x0000 (0x0290 - 0x0290)
class UBP_ZT_Survival_C final : public UFortZoneTheme
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ZT_Survival_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ZT_Survival_C")
	}
	static class UBP_ZT_Survival_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ZT_Survival_C>();
	}
};
DUMPER7_ASSERTS_UBP_ZT_Survival_C;

}

