#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CampaignMapPage_Stonewood_10

#include "Basic.hpp"


namespace SDK::Params
{

// Function CampaignMapPage_Stonewood_10.CampaignMapPage_Stonewood_10_C.ExecuteUbergraph_CampaignMapPage_Stonewood_10
// 0x0004 (0x0004 - 0x0000)
struct CampaignMapPage_Stonewood_10_C_ExecuteUbergraph_CampaignMapPage_Stonewood_10 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_CampaignMapPage_Stonewood_10_C_ExecuteUbergraph_CampaignMapPage_Stonewood_10;

}

