#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CampaignMapPage_Plankerton_09

#include "Basic.hpp"


namespace SDK::Params
{

// Function CampaignMapPage_Plankerton_09.CampaignMapPage_Plankerton_09_C.ExecuteUbergraph_CampaignMapPage_Plankerton_09
// 0x0004 (0x0004 - 0x0000)
struct CampaignMapPage_Plankerton_09_C_ExecuteUbergraph_CampaignMapPage_Plankerton_09 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_CampaignMapPage_Plankerton_09_C_ExecuteUbergraph_CampaignMapPage_Plankerton_09;

}

