#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ConversationUtil

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ConversationUtil.ConversationUtil_C
// 0x0008 (0x0248 - 0x0240)
class UConversationUtil_C final : public UFortJournalQuestDetails
{
public:
	class UFortConversation*                      Conversation;                                      // 0x0240(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void StartConversation(class UFortConversation* Conversation_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ConversationUtil_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ConversationUtil_C")
	}
	static class UConversationUtil_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConversationUtil_C>();
	}
};
DUMPER7_ASSERTS_UConversationUtil_C;

}

