#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Female_Commando_01_Skeleton_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Female_Commando_01_Skeleton_AnimBP.Female_Commando_01_Skeleton_AnimBP_C
// 0x0058 (0x0468 - 0x0410)
class UFemale_Commando_01_Skeleton_AnimBP_C final : public UCustomCharacterPartAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0410(0x0008)(Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_3D36AA2D48E736954157ABB046C8C983; // 0x0418(0x0048)()
	class USkeletalMeshComponent*                 MeshToCopy;                                        // 0x0460(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Female_Commando_01_Skeleton_AnimBP(int32 EntryPoint);
	void BlueprintInitializeAnimation();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Female_Commando_01_Skeleton_AnimBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Female_Commando_01_Skeleton_AnimBP_C")
	}
	static class UFemale_Commando_01_Skeleton_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFemale_Commando_01_Skeleton_AnimBP_C>();
	}
};
DUMPER7_ASSERTS_UFemale_Commando_01_Skeleton_AnimBP_C;

}

