#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Ranged_GenericDamage

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Ranged_GenericDamage.GA_Ranged_GenericDamage_C
// 0x0000 (0x0A80 - 0x0A80)
class UGA_Ranged_GenericDamage_C : public UFortGameplayAbility_RangedWeapon
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Ranged_GenericDamage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Ranged_GenericDamage_C")
	}
	static class UGA_Ranged_GenericDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Ranged_GenericDamage_C>();
	}
};
DUMPER7_ASSERTS_UGA_Ranged_GenericDamage_C;

}

