#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Commando_IncendiaryRoundsActive

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_Commando_IncendiaryRoundsActive.GCN_Commando_IncendiaryRoundsActive_C
// 0x0000 (0x0468 - 0x0468)
class AGCN_Commando_IncendiaryRoundsActive_C final : public AFortGameplayCueNotify_Looping
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_Commando_IncendiaryRoundsActive_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_Commando_IncendiaryRoundsActive_C")
	}
	static class AGCN_Commando_IncendiaryRoundsActive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_Commando_IncendiaryRoundsActive_C>();
	}
};
DUMPER7_ASSERTS_AGCN_Commando_IncendiaryRoundsActive_C;

}

