#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Map_Athena_StartingShields

#include "Basic.hpp"

#include "GE_Map_Fortitude_To_Health_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Map_Athena_StartingShields.GE_Map_Athena_StartingShields_C
// 0x0000 (0x0660 - 0x0660)
class UGE_Map_Athena_StartingShields_C final : public UGE_Map_Fortitude_To_Health_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Map_Athena_StartingShields_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Map_Athena_StartingShields_C")
	}
	static class UGE_Map_Athena_StartingShields_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Map_Athena_StartingShields_C>();
	}
};
DUMPER7_ASSERTS_UGE_Map_Athena_StartingShields_C;

}

