#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Outlander_LlamaFragment

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Outlander_LlamaFragment.GE_Outlander_LlamaFragment_C
// 0x0000 (0x0660 - 0x0660)
class UGE_Outlander_LlamaFragment_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Outlander_LlamaFragment_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Outlander_LlamaFragment_C")
	}
	static class UGE_Outlander_LlamaFragment_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Outlander_LlamaFragment_C>();
	}
};
DUMPER7_ASSERTS_UGE_Outlander_LlamaFragment_C;

}

