#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemDescriptionDetailWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ItemDescriptionDetailWidget.ItemDescriptionDetailWidget_C
// 0x0018 (0x0290 - 0x0278)
class UItemDescriptionDetailWidget_C final : public UFortItemDetailElementWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(Transient, DuplicateTransient)
	class UCommonTextBlock*                       ItemDescriptionTextBlock;                          // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          ShouldShowOnlyIfItemIsSimple;                      // 0x0288(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          InCollectionBook;                                  // 0x0289(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ItemDescriptionDetailWidget(int32 EntryPoint);
	void HandlePostDifferentItemToDetailSet();
	void IsItemSimple(bool* Result);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ItemDescriptionDetailWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ItemDescriptionDetailWidget_C")
	}
	static class UItemDescriptionDetailWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemDescriptionDetailWidget_C>();
	}
};
DUMPER7_ASSERTS_UItemDescriptionDetailWidget_C;

}

