#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemPerksListDetailWidget

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ItemPerksListDetailWidget.ItemPerksListDetailWidget_C
// 0x0018 (0x0290 - 0x0278)
class UItemPerksListDetailWidget_C final : public UFortItemDetailElementWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(Transient, DuplicateTransient)
	class UPerksList_C*                           PerksList;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          ShowActiveAbilitiesOnly;                           // 0x0288(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ItemPerksListDetailWidget(int32 EntryPoint);
	void HandlePostDifferentItemToDetailSet();
	void SetState(EFortPerksWidgetState InState, class UFortHero* InEvolutionOption);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ItemPerksListDetailWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ItemPerksListDetailWidget_C")
	}
	static class UItemPerksListDetailWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemPerksListDetailWidget_C>();
	}
};
DUMPER7_ASSERTS_UItemPerksListDetailWidget_C;

}

