#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemDetailsHeaderRarityTypeText

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ItemDetailsHeaderRarityTypeText.ItemDetailsHeaderRarityTypeText_C
// 0x0018 (0x0290 - 0x0278)
class UItemDetailsHeaderRarityTypeText_C final : public UFortItemDetailElementWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(Transient, DuplicateTransient)
	class UCommonTextBlock*                       RarityTextBlock;                                   // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       TypeTextBlock;                                     // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ItemDetailsHeaderRarityTypeText(int32 EntryPoint);
	void HandlePostDifferentItemToCompareWithSet();
	void HandlePostDifferentItemToDetailSet();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ItemDetailsHeaderRarityTypeText_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ItemDetailsHeaderRarityTypeText_C")
	}
	static class UItemDetailsHeaderRarityTypeText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemDetailsHeaderRarityTypeText_C>();
	}
};
DUMPER7_ASSERTS_UItemDetailsHeaderRarityTypeText_C;

}

