#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemView

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ItemView.ItemView_C
// 0x0000 (0x0320 - 0x0320)
class UItemView_C final : public UFortItemView
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ItemView_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ItemView_C")
	}
	static class UItemView_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemView_C>();
	}
};
DUMPER7_ASSERTS_UItemView_C;

}

