#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemInspectionItemExtraDetailsHostPanel

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ItemInspectionItemExtraDetailsHostPanel.ItemInspectionItemExtraDetailsHostPanel_C
// 0x0000 (0x02A0 - 0x02A0)
class UItemInspectionItemExtraDetailsHostPanel_C final : public UFortItemDetailsHostPanel
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ItemInspectionItemExtraDetailsHostPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ItemInspectionItemExtraDetailsHostPanel_C")
	}
	static class UItemInspectionItemExtraDetailsHostPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemInspectionItemExtraDetailsHostPanel_C>();
	}
};
DUMPER7_ASSERTS_UItemInspectionItemExtraDetailsHostPanel_C;

}

