#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JournalObjectiveEntry

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass JournalObjectiveEntry.JournalObjectiveEntry_C
// 0x0020 (0x0260 - 0x0240)
class UJournalObjectiveEntry_C final : public UFortListItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0240(0x0008)(Transient, DuplicateTransient)
	class UCommonTextBlock*                       CommonText_TaskName;                               // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UJournalObjectiveProgressWidget_C*      ProgressWidget;                                    // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFortQuestObjectiveInfo*                Objective;                                         // 0x0258(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_JournalObjectiveEntry(int32 EntryPoint);
	void Handle_Quests_Updated();
	void Construct();
	void SetData(class UObject* InData);
	void UpdateProgress(class UFortQuestObjectiveInfo* Objective_0);
	void Update(class UFortQuestObjectiveInfo* Objective_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("JournalObjectiveEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JournalObjectiveEntry_C")
	}
	static class UJournalObjectiveEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJournalObjectiveEntry_C>();
	}
};
DUMPER7_ASSERTS_UJournalObjectiveEntry_C;

}

