#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LeaderboardRowWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass LeaderboardRowWidget.LeaderboardRowWidget_C
// 0x0020 (0x08D0 - 0x08B0)
class ULeaderboardRowWidget_C final : public UFortLeaderboardEntryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08B0(0x0008)(Transient, DuplicateTransient)
	class UCommonTextBlock*                       Rank;                                              // 0x08B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       StatValue;                                         // 0x08C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       User;                                              // 0x08C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_LeaderboardRowWidget(int32 EntryPoint);
	void OnLeaderboardEntryDataSet();
	void SetDataDirect(class UFortLeaderboardRowProxyInstance* NewData);
	void Refresh(class UFortLeaderboardRowProxyInstance* RowObject);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LeaderboardRowWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LeaderboardRowWidget_C")
	}
	static class ULeaderboardRowWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULeaderboardRowWidget_C>();
	}
};
DUMPER7_ASSERTS_ULeaderboardRowWidget_C;

}

