#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LegacyButtonStyle_Item

#include "Basic.hpp"

#include "LegacyButtonStyle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LegacyButtonStyle-Item.LegacyButtonStyle-Item_C
// 0x0000 (0x1C08 - 0x1C08)
class ULegacyButtonStyle_Item_C final : public ULegacyButtonStyle_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LegacyButtonStyle-Item_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LegacyButtonStyle-Item_C")
	}
	static class ULegacyButtonStyle_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULegacyButtonStyle_Item_C>();
	}
};
DUMPER7_ASSERTS_ULegacyButtonStyle_Item_C;

}

