#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: M_MED_Commando_Head_HW01_Skeleton_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass M_MED_Commando_Head_HW01_Skeleton_AnimBP.M_MED_Commando_Head_HW01_Skeleton_AnimBP_C
// 0x00F0 (0x0448 - 0x0358)
class UM_MED_Commando_Head_HW01_Skeleton_AnimBP_C final : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0358(0x0008)(Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_D438209241CBEA7C1261418DAF6624DF; // 0x0360(0x0048)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh_776F9A9C4585632E302BAC964523BC4C; // 0x03A8(0x0098)(ContainsInstancedReference)
	class USkeletalMeshComponent*                 MeshToCopy;                                        // 0x0440(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_M_MED_Commando_Head_HW01_Skeleton_AnimBP(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Commando_Head_HW01_Skeleton_AnimBP_AnimGraphNode_CopyPoseFromMesh_776F9A9C4585632E302BAC964523BC4C();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("M_MED_Commando_Head_HW01_Skeleton_AnimBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"M_MED_Commando_Head_HW01_Skeleton_AnimBP_C")
	}
	static class UM_MED_Commando_Head_HW01_Skeleton_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UM_MED_Commando_Head_HW01_Skeleton_AnimBP_C>();
	}
};
DUMPER7_ASSERTS_UM_MED_Commando_Head_HW01_Skeleton_AnimBP_C;

}

