#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Node

#include "Basic.hpp"


namespace SDK::Params
{

// Function Node.Node_C.ExecuteUbergraph_Node
// 0x0008 (0x0008 - 0x0000)
struct Node_C_ExecuteUbergraph_Node final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Node_C_ExecuteUbergraph_Node;

// Function Node.Node_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct Node_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Node_C_PreConstruct;

// Function Node.Node_C.SetHighContrastMode
// 0x0001 (0x0001 - 0x0000)
struct Node_C_SetHighContrastMode final
{
public:
	bool                                          ActivateHighContrast;                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Node_C_SetHighContrastMode;

}

