#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuestTrackerEntry

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass QuestTrackerEntry.QuestTrackerEntry_C
// 0x0010 (0x02A8 - 0x0298)
class UQuestTrackerEntry_C final : public UFortQuestTrackerEntry
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(Transient, DuplicateTransient)
	class UImage*                                 SeparatorLine;                                     // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_QuestTrackerEntry(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("QuestTrackerEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QuestTrackerEntry_C")
	}
	static class UQuestTrackerEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuestTrackerEntry_C>();
	}
};
DUMPER7_ASSERTS_UQuestTrackerEntry_C;

}

