#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Transylvania_LightMaster

#include "Basic.hpp"

#include "Parent_BuildingPropActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Transylvania_LightMaster.Transylvania_LightMaster_C
// 0x0000 (0x10E0 - 0x10E0)
class ATransylvania_LightMaster_C : public AParent_BuildingPropActor_C
{
public:
	uint8                                         Pad_10D4[0x4];                                     // 0x10D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPointLightComponent*                   PointLight;                                        // 0x10D8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Transylvania_LightMaster_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Transylvania_LightMaster_C")
	}
	static class ATransylvania_LightMaster_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATransylvania_LightMaster_C>();
	}
};
DUMPER7_ASSERTS_ATransylvania_LightMaster_C;

}

